---
title: "ProgramHeader"
---
packet
0-31:    "segment_type"
32-63:   "segment_flags"
64-127:  "file_offset"
128-191: "virtual_address"
192-255: "physical_address"
256-319: "file_size"
320-383: "memory_size"
384-447: "alignment"
