---
title: "ElfSectionHeader"
---
packet
0-31:    "name"
32-63:   "section_type"
64-127:  "flags"
128-191: "addr"
192-255: "offset"
256-319: "size"
320-351: "link"
352-383: "info"
384-447: "addralign"
448-511: "entsize"
